import mongoose from 'mongoose';
import Car from '../models/Car.js';

/**
 * Comprehensive Car Database Seed
 * Includes Indian and Global brands with realistic data
 * Designed to scale to 1000+ cars
 */

const comprehensiveCars = [
  // ========== INDIAN BRANDS ==========
  
  // Maruti Suzuki
  {
    title: 'Maruti Suzuki Swift',
    brand: 'MARUTI',
    model: 'Swift',
    bodyType: 'Hatchback',
    fuelType: 'Petrol',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1197,
      cylinders: 4,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 88,
    torqueNm: 113,
    topSpeed: 165,
    zeroToHundred: 12.0,
    mileage: 23.2,
    price: {
      min: 599000,
      max: 899000,
      currency: 'INR',
    },
    launchYear: 2018,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    ],
    keyFeatures: ['Touchscreen Infotainment', 'ABS with EBD', 'Dual Airbags', 'Reverse Parking Camera'],
    pros: ['Excellent fuel economy', 'Low maintenance cost', 'Great resale value', 'Spacious cabin'],
    cons: ['Average build quality', 'Limited features in base variant'],
    tags: ['hatchback', 'petrol', 'budget', 'popular'],
    isFeatured: true,
  },
  {
    title: 'Maruti Suzuki Brezza',
    brand: 'MARUTI',
    model: 'Brezza',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1462,
      cylinders: 4,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 103,
    torqueNm: 138,
    topSpeed: 170,
    zeroToHundred: 11.5,
    mileage: 19.8,
    price: {
      min: 799000,
      max: 1399000,
      currency: 'INR',
    },
    launchYear: 2022,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['Sunroof', '360° Camera', 'Wireless Charging', '6 Airbags'],
    pros: ['Reliable engine', 'Good ground clearance', 'Feature-rich', 'Maruti service network'],
    cons: ['Premium pricing', 'Average interior quality'],
    tags: ['suv', 'petrol', 'compact', 'feature-rich'],
    isFeatured: true,
  },
  {
    title: 'Maruti Suzuki Dzire',
    brand: 'MARUTI',
    model: 'Dzire',
    bodyType: 'Sedan',
    fuelType: 'Petrol',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1197,
      cylinders: 4,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 88,
    torqueNm: 113,
    topSpeed: 160,
    zeroToHundred: 12.5,
    mileage: 23.3,
    price: {
      min: 649000,
      max: 999000,
      currency: 'INR',
    },
    launchYear: 2017,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200',
    keyFeatures: ['Touchscreen', 'ABS', 'Dual Airbags', 'Boot Space'],
    pros: ['Best-in-class mileage', 'Affordable', 'Low running cost'],
    cons: ['Basic features', 'Average performance'],
    tags: ['sedan', 'petrol', 'budget', 'mileage'],
    isFeatured: false,
  },

  // Hyundai
  {
    title: 'Hyundai Creta',
    brand: 'HYUNDAI',
    model: 'Creta',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1497,
      cylinders: 4,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 115,
    torqueNm: 144,
    topSpeed: 180,
    zeroToHundred: 11.2,
    mileage: 16.8,
    price: {
      min: 1099000,
      max: 1999000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['Panoramic Sunroof', 'Ventilated Seats', 'Bose Sound System', '360° Camera'],
    pros: ['Premium features', 'Comfortable ride', 'Good build quality', 'Modern design'],
    cons: ['Premium pricing', 'Average fuel economy'],
    tags: ['suv', 'petrol', 'premium', 'feature-rich'],
    isFeatured: true,
  },
  {
    title: 'Hyundai i20',
    brand: 'HYUNDAI',
    model: 'i20',
    bodyType: 'Hatchback',
    fuelType: 'Petrol',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1197,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 120,
    torqueNm: 172,
    topSpeed: 190,
    zeroToHundred: 9.5,
    mileage: 20.35,
    price: {
      min: 749000,
      max: 1199000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    keyFeatures: ['Wireless Charging', 'Bose Audio', 'Sunroof', 'Connected Car Tech'],
    pros: ['Sporty design', 'Feature-loaded', 'Good performance', 'Premium feel'],
    cons: ['Premium pricing', 'Average rear space'],
    tags: ['hatchback', 'petrol', 'premium', 'sporty'],
    isFeatured: true,
  },
  {
    title: 'Hyundai Venue',
    brand: 'HYUNDAI',
    model: 'Venue',
    bodyType: 'SUV',
    fuelType: 'Diesel',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1493,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 100,
    torqueNm: 240,
    topSpeed: 175,
    zeroToHundred: 12.0,
    mileage: 23.7,
    price: {
      min: 799000,
      max: 1399000,
      currency: 'INR',
    },
    launchYear: 2019,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['BlueLink Connected Car', 'Wireless Charging', 'Sunroof', 'Auto AC'],
    pros: ['Good fuel economy', 'Compact size', 'Feature-rich'],
    cons: ['Limited boot space', 'Average performance'],
    tags: ['suv', 'diesel', 'compact', 'connected'],
    isFeatured: false,
  },

  // Tata
  {
    title: 'Tata Nexon EV',
    brand: 'TATA',
    model: 'Nexon EV',
    bodyType: 'SUV',
    fuelType: 'EV',
    transmission: 'Automatic',
    driveType: 'FWD',
    engine: {
      displacement: 0,
      cylinders: 0,
      turbo: false,
      aspiration: 'Electric',
    },
    powerBHP: 129,
    torqueNm: 245,
    topSpeed: 120,
    zeroToHundred: 9.9,
    mileage: 0,
    range: 312,
    price: {
      min: 1499000,
      max: 1999000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    keyFeatures: ['ZConnect App', 'Regenerative Braking', 'Fast Charging', '7-inch Touchscreen'],
    pros: ['Zero emissions', 'Low running cost', '5-star safety', 'Good range'],
    cons: ['Charging infrastructure', 'Premium pricing'],
    tags: ['ev', 'suv', 'electric', 'safety'],
    isFeatured: true,
  },
  {
    title: 'Tata Harrier',
    brand: 'TATA',
    model: 'Harrier',
    bodyType: 'SUV',
    fuelType: 'Diesel',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1956,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 170,
    torqueNm: 350,
    topSpeed: 190,
    zeroToHundred: 9.5,
    mileage: 16.35,
    price: {
      min: 1499000,
      max: 2499000,
      currency: 'INR',
    },
    launchYear: 2019,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['JBL Sound System', 'Terrain Response Modes', 'Panoramic Sunroof', '6 Airbags'],
    pros: ['Robust build', 'Powerful engine', '5-star safety', 'Premium features'],
    cons: ['No petrol option', 'Heavy on fuel'],
    tags: ['suv', 'diesel', 'premium', 'safety'],
    isFeatured: true,
  },
  {
    title: 'Tata Altroz',
    brand: 'TATA',
    model: 'Altroz',
    bodyType: 'Hatchback',
    fuelType: 'Petrol',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1199,
      cylinders: 3,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 86,
    torqueNm: 113,
    topSpeed: 165,
    zeroToHundred: 13.0,
    mileage: 19.05,
    price: {
      min: 599000,
      max: 999000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    keyFeatures: ['5-Star Safety', 'Touchscreen Infotainment', 'Auto AC', 'Rear Parking Camera'],
    pros: ['5-star safety', 'Premium build', 'Spacious', 'Good value'],
    cons: ['Average performance', 'Limited features'],
    tags: ['hatchback', 'petrol', 'safety', 'budget'],
    isFeatured: false,
  },

  // Mahindra
  {
    title: 'Mahindra Thar',
    brand: 'MAHINDRA',
    model: 'Thar',
    bodyType: 'SUV',
    fuelType: 'Diesel',
    transmission: 'Manual',
    driveType: '4WD',
    engine: {
      displacement: 2198,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 130,
    torqueNm: 300,
    topSpeed: 155,
    zeroToHundred: 12.0,
    mileage: 15.2,
    price: {
      min: 1299000,
      max: 1699000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 4,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['4WD System', 'Removable Hard Top', 'Touchscreen', 'Off-road Capability'],
    pros: ['Excellent off-road', 'Iconic design', 'Powerful engine', 'Adventure-ready'],
    cons: ['Limited comfort', 'Low mileage', 'Long waiting period'],
    tags: ['suv', 'diesel', 'offroad', 'adventure'],
    isFeatured: true,
  },
  {
    title: 'Mahindra XUV700',
    brand: 'MAHINDRA',
    model: 'XUV700',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'FWD',
    engine: {
      displacement: 1997,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 200,
    torqueNm: 380,
    topSpeed: 200,
    zeroToHundred: 7.8,
    mileage: 12.0,
    price: {
      min: 1399000,
      max: 2699000,
      currency: 'INR',
    },
    launchYear: 2021,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 7,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['ADAS Technology', 'Sony Sound System', 'Panoramic Sunroof', '7-Seater Option'],
    pros: ['Powerful performance', 'Advanced features', 'Spacious', 'Value for money'],
    cons: ['Premium pricing', 'Average fuel economy'],
    tags: ['suv', 'petrol', 'premium', '7-seater'],
    isFeatured: true,
  },

  // ========== GLOBAL BRANDS ==========

  // Toyota
  {
    title: 'Toyota Innova Crysta',
    brand: 'TOYOTA',
    model: 'Innova Crysta',
    bodyType: 'MPV',
    fuelType: 'Diesel',
    transmission: 'Manual',
    driveType: 'RWD',
    engine: {
      displacement: 2393,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 150,
    torqueNm: 343,
    topSpeed: 180,
    zeroToHundred: 11.5,
    mileage: 13.68,
    price: {
      min: 1799000,
      max: 2699000,
      currency: 'INR',
    },
    launchYear: 2016,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 7,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    keyFeatures: ['7-Seater', 'Touchscreen', 'Rear AC Vents', 'Spacious Interior'],
    pros: ['Reliable', 'Spacious', 'Comfortable', 'Good resale value'],
    cons: ['Premium pricing', 'Heavy on fuel'],
    tags: ['mpv', 'diesel', '7-seater', 'family'],
    isFeatured: true,
  },
  {
    title: 'Toyota Camry Hybrid',
    brand: 'TOYOTA',
    model: 'Camry Hybrid',
    bodyType: 'Sedan',
    fuelType: 'Hybrid',
    transmission: 'CVT',
    driveType: 'FWD',
    engine: {
      displacement: 2494,
      cylinders: 4,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 218,
    torqueNm: 221,
    topSpeed: 180,
    zeroToHundred: 8.2,
    mileage: 23.27,
    price: {
      min: 4190000,
      max: 4290000,
      currency: 'INR',
    },
    launchYear: 2021,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200',
    keyFeatures: ['Hybrid Powertrain', 'Premium Interior', 'Safety Sense', 'Panoramic Roof'],
    pros: ['Excellent fuel economy', 'Premium quality', 'Smooth ride', 'Reliable'],
    cons: ['Expensive', 'Limited features'],
    tags: ['sedan', 'hybrid', 'premium', 'luxury'],
    isFeatured: true,
  },

  // Honda
  {
    title: 'Honda City',
    brand: 'HONDA',
    model: 'City',
    bodyType: 'Sedan',
    fuelType: 'Petrol',
    transmission: 'CVT',
    driveType: 'FWD',
    engine: {
      displacement: 1498,
      cylinders: 4,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 121,
    torqueNm: 145,
    topSpeed: 180,
    zeroToHundred: 10.5,
    mileage: 17.8,
    price: {
      min: 1199000,
      max: 1699000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200',
    keyFeatures: ['Honda Sensing', 'Lane Watch Camera', 'Sunroof', '8-Speaker Audio'],
    pros: ['Refined engine', 'Premium feel', 'Good features', 'Reliable'],
    cons: ['Premium pricing', 'Average rear space'],
    tags: ['sedan', 'petrol', 'premium', 'reliable'],
    isFeatured: true,
  },
  {
    title: 'Honda Amaze',
    brand: 'HONDA',
    model: 'Amaze',
    bodyType: 'Sedan',
    fuelType: 'Diesel',
    transmission: 'Manual',
    driveType: 'FWD',
    engine: {
      displacement: 1498,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 100,
    torqueNm: 200,
    topSpeed: 170,
    zeroToHundred: 12.0,
    mileage: 27.4,
    price: {
      min: 699000,
      max: 999000,
      currency: 'INR',
    },
    launchYear: 2018,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200',
    keyFeatures: ['Touchscreen', 'Reverse Camera', 'Auto AC', 'ABS'],
    pros: ['Excellent mileage', 'Reliable', 'Good value', 'Spacious'],
    cons: ['Basic features', 'Average performance'],
    tags: ['sedan', 'diesel', 'budget', 'mileage'],
    isFeatured: false,
  },

  // BMW
  {
    title: 'BMW 3 Series',
    brand: 'BMW',
    model: '3 Series',
    bodyType: 'Sedan',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'RWD',
    engine: {
      displacement: 1998,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 255,
    torqueNm: 400,
    topSpeed: 250,
    zeroToHundred: 6.2,
    mileage: 15.3,
    price: {
      min: 4290000,
      max: 4990000,
      currency: 'INR',
    },
    launchYear: 2019,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['BMW iDrive', 'Panoramic Sunroof', 'Wireless Charging', 'Adaptive LED Headlights'],
    pros: ['Sporty handling', 'Premium quality', 'Powerful engine', 'Advanced tech'],
    cons: ['Expensive', 'High maintenance'],
    tags: ['sedan', 'petrol', 'luxury', 'sporty'],
    isFeatured: true,
  },
  {
    title: 'BMW X5',
    brand: 'BMW',
    model: 'X5',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'AWD',
    engine: {
      displacement: 2998,
      cylinders: 6,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 340,
    torqueNm: 450,
    topSpeed: 243,
    zeroToHundred: 5.5,
    mileage: 11.2,
    price: {
      min: 7990000,
      max: 9990000,
      currency: 'INR',
    },
    launchYear: 2019,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['xDrive AWD', 'BMW Live Cockpit', 'Panoramic Sunroof', 'Air Suspension'],
    pros: ['Luxurious', 'Powerful', 'Advanced features', 'Premium build'],
    cons: ['Very expensive', 'High running cost'],
    tags: ['suv', 'petrol', 'luxury', 'premium'],
    isFeatured: true,
  },
  {
    title: 'BMW X1',
    brand: 'BMW',
    model: 'X1',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'DCT',
    driveType: 'FWD',
    engine: {
      displacement: 1998,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 192,
    torqueNm: 280,
    topSpeed: 230,
    zeroToHundred: 7.7,
    mileage: 14.82,
    price: {
      min: 4290000,
      max: 4990000,
      currency: 'INR',
    },
    launchYear: 2022,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['BMW iDrive 9', 'Panoramic Sunroof', 'Wireless Charging', 'Harman Kardon Audio'],
    pros: ['Compact luxury SUV', 'Good performance', 'Premium brand', 'Feature-rich'],
    cons: ['Expensive', 'Limited space'],
    tags: ['suv', 'petrol', 'luxury', 'compact'],
    isFeatured: false,
  },

  // Mercedes-Benz
  {
    title: 'Mercedes-Benz C-Class',
    brand: 'MERCEDES',
    model: 'C-Class',
    bodyType: 'Sedan',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'RWD',
    engine: {
      displacement: 1991,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 204,
    torqueNm: 300,
    topSpeed: 250,
    zeroToHundred: 7.3,
    mileage: 14.5,
    price: {
      min: 4490000,
      max: 5290000,
      currency: 'INR',
    },
    launchYear: 2021,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200',
    keyFeatures: ['MBUX Infotainment', 'Panoramic Sunroof', 'Burmester Sound', '64-Color Ambient Lighting'],
    pros: ['Luxurious interior', 'Premium brand', 'Advanced tech', 'Comfortable'],
    cons: ['Expensive', 'High maintenance'],
    tags: ['sedan', 'petrol', 'luxury', 'premium'],
    isFeatured: true,
  },
  {
    title: 'Mercedes-Benz GLC',
    brand: 'MERCEDES',
    model: 'GLC',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'AWD',
    engine: {
      displacement: 1991,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 197,
    torqueNm: 320,
    topSpeed: 230,
    zeroToHundred: 7.8,
    mileage: 12.0,
    price: {
      min: 5790000,
      max: 6990000,
      currency: 'INR',
    },
    launchYear: 2022,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['4MATIC AWD', 'MBUX', 'Panoramic Sunroof', 'Air Suspension'],
    pros: ['Luxurious SUV', 'Premium quality', 'Good features', 'Comfortable'],
    cons: ['Very expensive', 'High running cost'],
    tags: ['suv', 'petrol', 'luxury', 'premium'],
    isFeatured: true,
  },

  // Audi
  {
    title: 'Audi A4',
    brand: 'AUDI',
    model: 'A4',
    bodyType: 'Sedan',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'FWD',
    engine: {
      displacement: 1984,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 190,
    torqueNm: 320,
    topSpeed: 250,
    zeroToHundred: 7.3,
    mileage: 15.2,
    price: {
      min: 4290000,
      max: 4990000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200',
    keyFeatures: ['Virtual Cockpit', 'MMI Touch', 'Panoramic Sunroof', 'Bang & Olufsen Audio'],
    pros: ['Premium quality', 'Advanced tech', 'Good performance', 'Luxurious'],
    cons: ['Expensive', 'High maintenance'],
    tags: ['sedan', 'petrol', 'luxury', 'premium'],
    isFeatured: true,
  },
  {
    title: 'Audi Q5',
    brand: 'AUDI',
    model: 'Q5',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'AWD',
    engine: {
      displacement: 1984,
      cylinders: 4,
      turbo: true,
      aspiration: 'Turbo',
    },
    powerBHP: 252,
    torqueNm: 370,
    topSpeed: 237,
    zeroToHundred: 6.3,
    mileage: 12.0,
    price: {
      min: 5990000,
      max: 6990000,
      currency: 'INR',
    },
    launchYear: 2021,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['quattro AWD', 'Virtual Cockpit', 'Panoramic Sunroof', 'Matrix LED'],
    pros: ['Premium SUV', 'Powerful', 'Advanced tech', 'Luxurious'],
    cons: ['Very expensive', 'High running cost'],
    tags: ['suv', 'petrol', 'luxury', 'premium'],
    isFeatured: true,
  },

  // Porsche
  {
    title: 'Porsche 911',
    brand: 'PORSCHE',
    model: '911',
    bodyType: 'Sports',
    fuelType: 'Petrol',
    transmission: 'DCT',
    driveType: 'RWD',
    engine: {
      displacement: 2981,
      cylinders: 6,
      turbo: true,
      aspiration: 'Twin-Turbo',
    },
    powerBHP: 450,
    torqueNm: 530,
    topSpeed: 308,
    zeroToHundred: 3.7,
    mileage: 8.5,
    price: {
      min: 16900000,
      max: 19900000,
      currency: 'INR',
    },
    launchYear: 2019,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 4,
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200',
    keyFeatures: ['PDK Transmission', 'Sport Chrono', 'PASM', 'Premium Sound'],
    pros: ['Iconic design', 'Exceptional performance', 'Premium quality', 'Track-ready'],
    cons: ['Very expensive', 'Impractical', 'High running cost'],
    tags: ['sports', 'petrol', 'supercar', 'performance'],
    isFeatured: true,
  },
  {
    title: 'Porsche Macan',
    brand: 'PORSCHE',
    model: 'Macan',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'DCT',
    driveType: 'AWD',
    engine: {
      displacement: 2894,
      cylinders: 6,
      turbo: true,
      aspiration: 'Twin-Turbo',
    },
    powerBHP: 380,
    torqueNm: 520,
    topSpeed: 254,
    zeroToHundred: 4.8,
    mileage: 10.0,
    price: {
      min: 7990000,
      max: 9990000,
      currency: 'INR',
    },
    launchYear: 2021,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['PDK Transmission', 'Sport Chrono', 'Air Suspension', 'Premium Interior'],
    pros: ['Sporty SUV', 'Powerful', 'Premium brand', 'Good handling'],
    cons: ['Very expensive', 'High running cost'],
    tags: ['suv', 'petrol', 'luxury', 'sporty'],
    isFeatured: true,
  },

  // Ferrari
  {
    title: 'Ferrari 488 GTB',
    brand: 'FERRARI',
    model: '488 GTB',
    bodyType: 'Supercar',
    fuelType: 'Petrol',
    transmission: 'DCT',
    driveType: 'RWD',
    engine: {
      displacement: 3902,
      cylinders: 8,
      turbo: true,
      aspiration: 'Twin-Turbo',
    },
    powerBHP: 670,
    torqueNm: 760,
    topSpeed: 330,
    zeroToHundred: 3.0,
    mileage: 5.0,
    price: {
      min: 34900000,
      max: 39900000,
      currency: 'INR',
    },
    launchYear: 2015,
    discontinued: true,
    safetyRating: 4,
    seatingCapacity: 2,
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200',
    keyFeatures: ['F1-Trac', 'E-Diff', 'Manettino', 'Carbon Ceramic Brakes'],
    pros: ['Exotic design', 'Extreme performance', 'Racing heritage', 'Exclusive'],
    cons: ['Extremely expensive', 'Impractical', 'Very high maintenance'],
    tags: ['supercar', 'petrol', 'exotic', 'performance'],
    isFeatured: true,
  },
  {
    title: 'Ferrari Portofino',
    brand: 'FERRARI',
    model: 'Portofino',
    bodyType: 'Coupe',
    fuelType: 'Petrol',
    transmission: 'DCT',
    driveType: 'RWD',
    engine: {
      displacement: 3855,
      cylinders: 8,
      turbo: true,
      aspiration: 'Twin-Turbo',
    },
    powerBHP: 600,
    torqueNm: 760,
    topSpeed: 320,
    zeroToHundred: 3.5,
    mileage: 5.5,
    price: {
      min: 39900000,
      max: 44900000,
      currency: 'INR',
    },
    launchYear: 2018,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 2,
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200',
    keyFeatures: ['Retractable Hardtop', 'F1-Trac', 'E-Diff', 'Premium Interior'],
    pros: ['Convertible', 'Powerful', 'Exotic', 'Luxurious'],
    cons: ['Extremely expensive', 'Impractical', 'High maintenance'],
    tags: ['coupe', 'petrol', 'exotic', 'convertible'],
    isFeatured: true,
  },

  // Lamborghini
  {
    title: 'Lamborghini Huracán',
    brand: 'LAMBORGHINI',
    model: 'Huracán',
    bodyType: 'Supercar',
    fuelType: 'Petrol',
    transmission: 'DCT',
    driveType: 'AWD',
    engine: {
      displacement: 5204,
      cylinders: 10,
      turbo: false,
      aspiration: 'NA',
    },
    powerBHP: 640,
    torqueNm: 600,
    topSpeed: 325,
    zeroToHundred: 2.9,
    mileage: 4.5,
    price: {
      min: 32900000,
      max: 39900000,
      currency: 'INR',
    },
    launchYear: 2014,
    discontinued: false,
    safetyRating: 4,
    seatingCapacity: 2,
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200',
    keyFeatures: ['LDVI System', 'ANIMA Modes', 'Carbon Ceramic Brakes', 'Premium Sound'],
    pros: ['Exotic design', 'Extreme performance', 'V10 engine', 'Exclusive'],
    cons: ['Extremely expensive', 'Impractical', 'Very high maintenance'],
    tags: ['supercar', 'petrol', 'exotic', 'performance'],
    isFeatured: true,
  },
  {
    title: 'Lamborghini Urus',
    brand: 'LAMBORGHINI',
    model: 'Urus',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    driveType: 'AWD',
    engine: {
      displacement: 3996,
      cylinders: 8,
      turbo: true,
      aspiration: 'Twin-Turbo',
    },
    powerBHP: 650,
    torqueNm: 850,
    topSpeed: 305,
    zeroToHundred: 3.6,
    mileage: 7.8,
    price: {
      min: 39900000,
      max: 44900000,
      currency: 'INR',
    },
    launchYear: 2018,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['ANIMA Modes', 'Air Suspension', 'Carbon Ceramic Brakes', 'Premium Interior'],
    pros: ['Supercar SUV', 'Extreme performance', 'Practical', 'Exclusive'],
    cons: ['Extremely expensive', 'High running cost', 'High maintenance'],
    tags: ['suv', 'petrol', 'exotic', 'performance'],
    isFeatured: true,
  },

  // Tesla
  {
    title: 'Tesla Model 3',
    brand: 'TESLA',
    model: 'Model 3',
    bodyType: 'Sedan',
    fuelType: 'EV',
    transmission: 'Automatic',
    driveType: 'RWD',
    engine: {
      displacement: 0,
      cylinders: 0,
      turbo: false,
      aspiration: 'Electric',
    },
    powerBHP: 283,
    torqueNm: 404,
    topSpeed: 225,
    zeroToHundred: 5.3,
    mileage: 0,
    range: 491,
    price: {
      min: 5990000,
      max: 6990000,
      currency: 'INR',
    },
    launchYear: 2019,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    keyFeatures: ['Autopilot', 'Supercharger Network', '15-inch Touchscreen', 'Over-the-Air Updates'],
    pros: ['Zero emissions', 'Low running cost', 'Advanced tech', 'Good range'],
    cons: ['Charging infrastructure', 'Premium pricing', 'Build quality concerns'],
    tags: ['ev', 'sedan', 'electric', 'tech'],
    isFeatured: true,
  },
  {
    title: 'Tesla Model Y',
    brand: 'TESLA',
    model: 'Model Y',
    bodyType: 'SUV',
    fuelType: 'EV',
    transmission: 'Automatic',
    driveType: 'AWD',
    engine: {
      displacement: 0,
      cylinders: 0,
      turbo: false,
      aspiration: 'Electric',
    },
    powerBHP: 384,
    torqueNm: 660,
    topSpeed: 250,
    zeroToHundred: 4.8,
    mileage: 0,
    range: 533,
    price: {
      min: 6990000,
      max: 7990000,
      currency: 'INR',
    },
    launchYear: 2020,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 7,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200',
    keyFeatures: ['Autopilot', '7-Seater Option', 'Supercharger', 'Panoramic Glass Roof'],
    pros: ['Spacious', 'Good range', 'Advanced tech', 'Zero emissions'],
    cons: ['Charging infrastructure', 'Premium pricing', 'Build quality'],
    tags: ['ev', 'suv', 'electric', 'tech'],
    isFeatured: true,
  },
  {
    title: 'Tesla Model S Plaid',
    brand: 'TESLA',
    model: 'Model S Plaid',
    bodyType: 'Sedan',
    fuelType: 'EV',
    transmission: 'Automatic',
    driveType: 'AWD',
    engine: {
      displacement: 0,
      cylinders: 0,
      turbo: false,
      aspiration: 'Electric',
    },
    powerBHP: 1020,
    torqueNm: 1420,
    topSpeed: 322,
    zeroToHundred: 2.1,
    mileage: 0,
    range: 628,
    price: {
      min: 12900000,
      max: 14900000,
      currency: 'INR',
    },
    launchYear: 2021,
    discontinued: false,
    safetyRating: 5,
    seatingCapacity: 5,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200',
    keyFeatures: ['Plaid Powertrain', '17-inch Touchscreen', 'Autopilot', 'Ludicrous Mode'],
    pros: ['Extreme performance', 'Long range', 'Advanced tech', 'Zero emissions'],
    cons: ['Very expensive', 'Charging infrastructure', 'Build quality'],
    tags: ['ev', 'sedan', 'electric', 'performance'],
    isFeatured: true,
  },
];

/**
 * Seed cars into database
 * Only inserts if collection is empty (prevents duplicates)
 */
export const seedCars = async () => {
  const session = await mongoose.startSession();
  session.startTransaction();
  try {
    const count = await Car.countDocuments();
    if (count > 0) {
      await session.commitTransaction();
      session.endSession();
      return { skipped: true, count, message: 'Database already has cars. Use force flag to re-seed.' };
    }

    // Transform data to match schema (handle legacy price format)
    const carsToInsert = comprehensiveCars.map((car) => {
      // If price is a number, convert to price object
      if (typeof car.price === 'number') {
        return {
          ...car,
          price: {
            min: car.price,
            max: car.price,
            currency: 'INR',
          },
        };
      }
      return car;
    });

    const inserted = await Car.insertMany(carsToInsert, { session });
    await session.commitTransaction();
    session.endSession();
    
    return { 
      inserted: inserted.length,
      message: `Successfully inserted ${inserted.length} cars`,
      brands: [...new Set(inserted.map(c => c.brand))],
    };
  } catch (error) {
    await session.abortTransaction();
    session.endSession();
    throw error;
  }
};

/**
 * Force seed - clears existing data and re-seeds
 * Use with caution in production!
 */
export const forceSeedCars = async () => {
  const session = await mongoose.startSession();
  session.startTransaction();
  try {
    // Clear existing cars
    await Car.deleteMany({}, { session });
    
    // Transform and insert
    const carsToInsert = comprehensiveCars.map((car) => {
      if (typeof car.price === 'number') {
        return {
          ...car,
          price: {
            min: car.price,
            max: car.price,
            currency: 'INR',
          },
        };
      }
      return car;
    });

    const inserted = await Car.insertMany(carsToInsert, { session });
    await session.commitTransaction();
    session.endSession();
    
    return { 
      inserted: inserted.length,
      message: `Force seeded ${inserted.length} cars`,
      brands: [...new Set(inserted.map(c => c.brand))],
    };
  } catch (error) {
    await session.abortTransaction();
    session.endSession();
    throw error;
  }
};


